---

- name: Configure elk instance
  hosts: tag_web
  connection: ssh
  sudo: true

  tasks:
  - name: Install docker compose
    command: sudo curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose
    
  - name: Clone repo
    command: sudo git clone https://github.com/Olowokandi/ChallDev.git
      
  - name: Sysctl vm max set
    command: sudo sysctl -w vm.max_map_count=262144
  
  - name: Adding docker user to group
    command: sudo usermod -aG docker ${USER}

  - name: Restarting docker service
    command: sudo service docker restart 

  - name: Container setup
    command: cd ChallDev && sudo docker-compose up -d

- name: Configure app instance
  hosts: tag_app
  connection: ssh
  sudo: true

  tasks:
  - name: Adding docker user to group
    command: sudo usermod -aG docker ${USER}

  - name: Restarting docker service
    command: sudo service docker restart 

  - name: Install docker compose
    command: sudo curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose
  
  - name: copy docker-compose file
    copy: 
      src: /home/gbolahan/ChallDev/wordpress/docker-compose.yml
      dest: /home/gbolahan/docker-compose.yml

  - name: Container setup
    command: sudo docker-compose up -d