---

- name: Configure elk instance
  hosts: tag_web
  connection: ssh
  sudo: true
  roles:
  - { role: elk }
  - { role: 'sdarwin.nagios', run_nagios_client: true}

- name: Configure app instance
  hosts: tag_app
  connection: ssh
  sudo: true
  roles:
  - { role: wordpress }
  - { role: 'sdarwin.nagios', run_nagios_client: true}

- name: Configure nagios instance
  hosts: tag_nagios
  connection: ssh
  sudo: true
  roles:
  - { role: 'sdarwin.nagios', run_nagios_server: true}