---

- name: Configure elk instance
  hosts: tag_web
  connection: ssh
  sudo: true
  roles:
     - elk
     - nagios-client

- name: Configure app instance
  hosts: tag_app
  connection: ssh
  sudo: true
  roles:
     - wordpress
     - nagios-client

- name: Configure nagios instance
  hosts: tag_nagios
  connection: ssh
  sudo: true
  roles:
  - { role: nagios }