---
- name: Install docker compose
  command: sudo curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose 
    
- name: Mke compose executable
  command: sudo chmod +x /usr/local/bin/docker-compose

- name: Clone repo
  command: sudo git clone https://github.com/Olowokandi/ChallDev.git
  args: 
    creates: /home/gbolahan/ChallDev
      
- name: Sysctl vm max set
  command: sudo sysctl -w vm.max_map_count=262144
  
- name: Adding docker user to group
  command: sudo usermod -aG docker ${USER}

- name: Restarting docker service
  command: sudo service docker restart 

- name: Container setup
  command: sudo docker-compose up -d
  args:
    chdir: /home/gbolahan/ChallDev